[package]
name = "client"
version = "0.1.0"
edition = "2024"

[features]
watch_assets = ["bevy/embedded_watcher", "bevy/file_watcher"]

[lints]
workspace = true

[dependencies]
audio = { path = "../crates/audio", features = ["client"] }
bevy = { workspace = true, features = ["3d", "hdr", "jpeg", "ktx2", "tga", "ui"] }
bevy_dev_tools = "0.19.0"
bevy_egui = { workspace = true }
zstd = { workspace = true }
rapier3d = { workspace = true }
steamworks = "0.13.0"
serde = { workspace = true }
libc = "0.2"
ureq = { workspace = true }
dirs = "6.0.0"
toml = { version = "1.0.6", features = ["preserve_order"] }
# custom crates
common = { path = "../crates/common" }
http_common = { path = "../crates/http_common" }
physics = { path = "../crates/physics" }
gameplay = { path = "../crates/gameplay", features = ["client"] }
master_plugin = { path = "../crates/master_plugin", features = ["client"] }
particles_plugin = { path = "../crates/particles_plugin" }
