[package]
name = "client"
version = "0.1.0"
edition = "2024"

[lints]
workspace = true

[dependencies]
bevy = { workspace = true, features = ["3d", "jpeg", "tga"] }
bevy_egui = { workspace = true }
zstd = { workspace = true }
rapier3d = { workspace = true }
steamworks = "0.13.0"
serde = { workspace = true }
dirs = "6.0.0"
toml = { version = "1.0.6", features = ["preserve_order"] }
fmod = { package = "libfmod", git = "https://github.com/GageHowe/libfmod", rev = "1b8cb56" }

# custom crates
common = { path = "../crates/common" }
http_common = { path = "../crates/http_common" }
physics = { path = "../crates/physics" }
net = { path = "../crates/net", features = ["client"] }
game_objects = { path = "../crates/game_objects", features = ["client"] }
scripting = { path = "../crates/scripting", features = ["client"] }
master_plugin = { path = "../crates/master_plugin", features = ["client"] }
session = { path = "../crates/session", features = ["client"] }
bevy_hanabi_plugin = { path = "../crates/bevy_hanabi" }
# bevy_luna = { path = "../../bevy_raytrace" } # local testing
bevy_luna = { git = "https://github.com/GageHowe/bevy_luna.git" }
