[package]
name = "client"
version = "0.1.0"
edition = "2024"

[lints]
workspace = true

[dependencies]
bevy = { version = "0.18", default-features = false, features = ["jpeg", "std", "multi_threaded"] }
bevy_egui = "0.39.1"
zstd = "0.13.3"
rapier3d = { version = "0.32.0", features = ["simd-stable", "parallel"] }
bevy-steamworks = "0.16"
serde = { version = "1", features = ["derive"] }
dirs = "6.0.0"
toml = { version = "1.0.6", features = ["preserve_order"] }
fmod = { package = "libfmod", git = "https://github.com/GageHowe/libfmod", rev = "1b8cb56" }
ureq = { version = "2", features = ["json"] }

# custom crates

common = { path = "../crates/common" }
http_common = { path = "../crates/http_common" }
physics = { path = "../crates/physics" }
net = { path = "../crates/net", features = ["client"] }
game_objects = { path = "../crates/game_objects", features = ["client"] }
scripting = { path = "../crates/scripting" }
master_plugin = { path = "../crates/master_plugin", features = ["client"] }
