[package]
name = "net"
version = "0.1.0"
edition = "2024"

[lints]
workspace = true

[features]
client = []
server = []

[dependencies]
common = { path = "../common" }
bevy = { workspace = true, features = ["serialize", "std", "multi_threaded"] }
bytes = { workspace = true }
postcard = { workspace = true }
quinn = { workspace = true }
rcgen = { workspace = true }
rustls = { workspace = true }
serde = { workspace = true }
tokio = { workspace = true }
zstd = { workspace = true }
