[package]
name = "net"
version = "0.1.0"
edition = "2024"

[lints]
workspace = true

[features]
client = []
server = []

[dependencies]
common = { path = "../common" }
bevy = { version = "0.18", features = ["serialize", "std", "multi_threaded"] }
bytes = "1"
postcard = { version = "1", features = ["alloc"] }
quinn = "0.11"
rcgen = "0.13"
rustls = "0.23"
serde = { version = "1", features = ["derive"] }
tokio = { version = "1", features = ["rt-multi-thread", "sync", "time"] }
zstd = "0.13"
