[package]
name = "game_objects"
version = "0.1.0"
edition = "2024"

[lib]
path = "../lib.rs"

[features]
client = ["bevy/3d", "bevy/jpeg", "dep:bevy_egui", "dep:bevy_hanabi_plugin", "dep:noise-functions"]

[lints]
workspace = true

[dependencies]
common = { path = "../common" }
physics = { path = "../physics" }
net = { path = "../net" }
bevy = { workspace = true, features = ["https", "scene", "serialize", "std", "multi_threaded"] }
rapier3d = { workspace = true }
bitflags = { workspace = true }
bevy_egui = { workspace = true, optional = true }
bevy_hanabi_plugin = { path = "../bevy_hanabi", optional = true }
postcard = { workspace = true }
mlua = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
ron = { workspace = true }
zstd = { workspace = true }
fastrand = { workspace = true }
ureq = { workspace = true }
sha2 = { workspace = true }
noise-functions = { workspace = true, optional = true }
