#cargo-features = ["codegen-backend"]

[workspace]
members = ["crates/*", "gameserver", "client", "beacon", "tools/*"]
resolver = "3"

[workspace.lints.rust]
unused_must_use = "deny" # return values of functions marked with #[must_use] must not be ignored

[workspace.lints.clippy]

unwrap_used = "deny" # disallow unwrap
expect_used = "deny" # disallow expect
todo = "deny" # disallow checked-in todo placeholders
unimplemented = "deny" # disallow checked-in stubs
cognitive_complexity = "warn"
# cognitive_complexity currently shows nothing

too_many_arguments = "allow"
type_complexity = "allow" # warn erroneously warns against bevy ParamSets etc
# manual_find = "allow" # Don't force iter().find()

[profile.dev]
opt-level = 1
lto = false
incremental = false
strip = "debuginfo"

[profile.dev.package.rapier3d]
opt-level = 3
[profile.dev.package.parry3d]
opt-level = 3
[profile.dev.package.nalgebra]
opt-level = 3
[profile.dev.package.serde]
opt-level = 3
[profile.dev.package.postcard]
opt-level = 3
[profile.dev.package.zstd]
opt-level = 3
[profile.dev.package.bevy_ecs]
opt-level = 3
[profile.dev.package.bevy_transform]
opt-level = 3

[profile.release]
opt-level = 3
lto = "thin"
strip = true
codegen-units = 1
panic = "abort"
debug = 0

[profile.profiling]
inherits = "release"
debug = 1
strip = "none"
