#cargo-features = ["codegen-backend"]

[workspace]
members = [
    "crates/audio",
    "crates/asset_pak",
    "crates/particles_plugin",
    "crates/common",
    "crates/gameplay",
    "crates/http_common",
    "crates/master_plugin",
    "crates/physics",
    "gameserver",
    "client",
    "beacon",
    "tools/*",
]
resolver = "3"

[workspace.lints.rust]
unused_must_use = "deny" # return values of functions marked with #[must_use] must not be ignored

[workspace.lints.clippy]
perf = { level = "warn", priority = -1 }
style = { level = "warn", priority = -1 }
complexity = { level = "warn", priority = -1 }
suspicious = { level = "warn", priority = -1 }
unwrap_used = "deny"
expect_used = "deny"
cognitive_complexity = "warn"

wildcard_imports = "allow"
too_many_arguments = "allow"
type_complexity = "allow" # erroneously warns against bevy ParamSets etc
# manual_find = "allow" # Don't force iter().find()

[workspace.dependencies]
bevy = { version = "0.19", default-features = false }
rapier3d = { version = "=0.33.0-alpha", features = ["simd-stable", "parallel"] } # physics
bitflags = "2" # physics collider flags
serde = { version = "1", features = ["derive"] }
serde_json = "1"
postcard = { version = "1", features = ["alloc"] } # serialization
tokio = { version = "=1.52.0", features = ["rt-multi-thread", "sync", "time"] } # async
ron = "0.12.0"
zstd = "0.13.3" # compression
mlua = { version = "0.10", features = ["lua54", "vendored"] } # scripting
quinn = "0.11" # networking
rcgen = "0.13"
rustls = "0.23"
sha2 = "0.10.9"
fastrand = "2" # rng
bytes = "1"
ureq = { version = "2", features = ["json"] }
bevy_egui = "0.41.1"
noise-functions = "0.8.2"
chacha20poly1305 = "0.10" # encryption

[profile.dev]
opt-level = 1
lto = false
#incremental = false
strip = "debuginfo" # for compilation speed

# Optimize all dependencies even in debug builds (does not affect workspace packages):
[profile.dev.package."*"]
# opt-level = 3

[profile.release]
opt-level = 3
lto = "thin"
strip = true
codegen-units = 1
panic = "abort"
debug = 0

[profile.profiling]
inherits = "release"
debug = 1
strip = "none"
