edition = "2021"
max_width = 100

# reorder_imports = false
imports_granularity = "Crate" # group crate imports
group_imports = "StdExternalCrate" # separate std and custom crates
wrap_comments = false
use_small_heuristics = "Max" # aggressively keep things one line
use_field_init_shorthand = true
# cargo fmt --all
imports_granularity = "Crate"  # groups imports, won't explode globs into specifics
group_imports = "StdExternalCrate"
