[package]
name = "beacon"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = { version = "=0.8.8", features = ["macros"] }
serde = { workspace = true }
tokio = { workspace = true }
http_common = { path = "../crates/http_common" }
fastrand = { workspace = true }

# don't use minify-html, caddy already does html gzip compression
