[package]
name = "particles_plugin"
version = "0.1.0"
edition = "2024"

[lints]
workspace = true

[features]
default = []
particles = ["dep:hanabi"]

[dependencies]
bevy = { workspace = true, features = ["std", "multi_threaded"] }
hanabi = { package = "bevy_hanabi", git = "https://github.com/djeedai/bevy_hanabi", default-features = false, features = ["3d"], optional = true }
