[package]
name = "gameplay"
version = "0.1.0"
edition = "2024"

[lib]
path = "src/lib.rs"

[features]
client = ["bevy/3d", "bevy/jpeg", "dep:bevy_egui", "dep:particles_plugin", "dep:noise-functions"]
server = []

[lints]
workspace = true

[dependencies]
audio = { path = "../audio" }
common = { path = "../common" }
http_common = { path = "../http_common" }
physics = { path = "../physics" }
bevy = { workspace = true, features = ["https", "scene", "serialize", "std", "multi_threaded"] }
bytes = { workspace = true }
rapier3d = { workspace = true }
bitflags = { workspace = true }
bevy_egui = { workspace = true, optional = true }
particles_plugin = { path = "../particles_plugin", optional = true }
postcard = { workspace = true }
mlua = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
quinn = { workspace = true }
rcgen = { workspace = true }
rustls = { workspace = true }
ureq = { workspace = true }
ron = { workspace = true }
zstd = { workspace = true }
fastrand = { workspace = true }
sha2 = { workspace = true }
noise-functions = { workspace = true, optional = true }
