[package]
name = "physics"
version = "0.1.0"
edition = "2024"

[features]
client = []

[lints]
workspace = true

[dependencies]
common = { path = "../common" }
bevy = { version = "0.18", features = ["serialize", "std", "multi_threaded"] }
rapier3d = { version = "0.32.0", features = ["simd-stable", "parallel"] }
