
[package]
name = "gameserver"
version = "0.1.0"
edition = "2024"

[lints]
workspace = true

[dependencies]
game_common = { path = "../game_common" }
bevy = { version = "0.18", default-features = false, features = ["bevy_core_pipeline"] }
wincode = "0.4.1"
rapier3d = "0.32.0"
