
[package]
name = "gameserver"
version = "0.1.0"
edition = "2024"

[lints]
workspace = true

[dependencies]
common = { path = "../common" }
physics = { path = "../physics" }
net = { path = "../net" }
game_objects = { path = "../game_objects" }
scripting = { path = "../scripting" }
master_plugin = { path = "../master_plugin" }
bevy = { version = "0.18", default-features = false, features = ["bevy_log", "multi_threaded", "std"] }
