
[package]
name = "gameserver"
version = "0.1.0"
edition = "2024"

[lints]
workspace = true

[dependencies]
common = { path = "../crates/common" }
physics = { path = "../crates/physics" }
net = { path = "../crates/net" }
game_objects = { path = "../crates/game_objects" }
scripting = { path = "../crates/scripting" }
master_plugin = { path = "../crates/master_plugin" }
bevy = { version = "0.18", default-features = false, features = ["bevy_log", "multi_threaded", "std"] }
