
[target.x86_64-pc-windows-msvc]
linker = "rust-lld.exe"
rustflags = ["-C", "link-arg=-fuse-ld=lld"]

[profile.dev]
opt-level = 1
lto = false
#codegen-backend = "cranelift"

[profile.release]
opt-level = 3
#debug = true
lto = "thin"
strip = true
codegen-units = 1

# https://doc.rust-lang.org/beta/unstable-book/compiler-flags/debug_info_for_profiling.html
