# allows unique package features per binary
[unstable]
feature-unification = true
[resolver]
feature-unification = "package"

[target.aarch64-apple-darwin]
rustflags = ["-C", "link-arg=-fuse-ld=lld"]
