
[package]
name = "common"
version = "0.1.0"
edition = "2024"

[lints]
workspace = true

[dependencies]
bevy = { version = "0.18", default-features = false, features = ["bevy_log"] }
#bevy_ecs = "0.18"
#bevy_math = "0.18"
#bevy_time = "0.18"
#bincode = "2.0"
quinn = "0.11"
anyhow = "1"
rustls = { version = "0.23", default-features = false }
#rustls-pemfile = "2"
rapier3d = "0.32.0"
bevy_egui = "0.39.1"
wincode = "0.4.1"
wincode-derive = "0.4.0"
zstd = "0.13.3"
tokio = "1.49.0"
rcgen = "0.14.7"
bytes = "1.11.1"
