
[package]
name = "common"
version = "0.1.0"
edition = "2024"

[lints]
workspace = true

[dependencies]
bevy = { version = "0.18", features = ["serialize", "jpeg"] }
rapier3d = { version = "0.32.0", features = ["simd-stable", "parallel"] }
bevy_egui = "0.39.1"
postcard = { version = "1", features = ["alloc"] }
zstd = "0.13.3"
bevy_quinnet = { git = "https://github.com/GageHowe/bevy_quinnet_minimal", default-features = false, features = ["client", "server"] }
rhai = "1.24.0"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
ron = "0.12.0"
