[package]
name = "master_plugin"
version = "0.1.0"
edition = "2024"

[lints]
workspace = true

[features]
client = ["net/client", "scripting/client"]
server = ["net/server"]

[dependencies]
asset_pak = { path = "../asset_pak", features = ["bevy_reader"] }
gameplay = { path = "../gameplay" }
scripting = { path = "../scripting" }
common = { path = "../common" }
physics = { path = "../physics" }
net = { path = "../net" }
bevy = { workspace = true, features = ["std", "multi_threaded"] }
