[package]
name = "scripting"
version = "0.1.0"
edition = "2024"

[lints]
workspace = true

[features]
client = ["game_objects/client"]

[dependencies]
game_objects = { path = "../game_objects" }
common = { path = "../common" }
net = { path = "../net" }
physics = { path = "../physics" }
bevy = { workspace = true, features = ["serialize", "jpeg", "std", "multi_threaded"] }
rapier3d = { workspace = true }
mlua = { workspace = true }
